export const LOADER_TRUE = 'LOADER_TRUE';
export const LOADER_FALSE = 'LOADER_FALSE';
export const LOADING_PROGRESS = 'LOADING_PROGRESS';
export const LOADING_PROGRESS_COMPLETE = 'LOADING_PROGRESS_COMPLETE';
export const GET_INDICATOR = 'GET_INDICATOR';
export const SIGNUP = 'SIGNUP';
export const SIGNOUT = 'SIGNOUT';
export const SIGNIN = 'SIGNIN';

export const NOTIFICATION_READ = 'NOTIFICATION_READ';
export const UPDATE_COUNTER = 'UPDATE_COUNTER';
